image: registry.gitlab.com/shrugal/wow-packager:latest

stages:
  - build
  - test
  - deploy

before_script:
  - WOWI_ID=$(case $CI_COMMIT_TAG in *next*|*ptr*) echo $WOWI_ID_NEXT;; ""|*debug*|*alpha*|*beta*) echo $WOWI_ID_TEST;; *) echo $WOWI_ID;; esac)

.releases: &releases
  - /^\d(\.?\d+)*((-(next|ptr|live))?(-(debug|alpha|beta|stable))?\d+)?$/

build:
  stage: build
  only: *releases
  script:
    - release.sh -d
  artifacts:
    paths:
      - .release/PersoLootRoll/
      - .release/*.zip

quicktest:
  stage: test
  except: *releases
  variables:
    GIT_DEPTH: 1
    GIT_SUBMODULE_STRATEGY: normal
  script:
    - lua Test.lua

test:
  stage: test
  only: *releases
  variables:
    GIT_DEPTH: 1
    GIT_SUBMODULE_STRATEGY: normal
  script:
    - lua Test.lua -b
  
curseforge:
  stage: deploy
  only: *releases
  environment:
    name: CurseForge
    url: https://wow.curseforge.com/projects/persolootroll
  script:
    - release.sh -ocelzWAHG

wowinterface:
  stage: deploy
  only: *releases
  environment:
    name: WoWInterface
    url: https://www.wowinterface.com/downloads/info24667-PersoLootRoll.html
  script:
    - release.sh -ocelzLAHG

wago:
  stage: deploy
  only: *releases
  environment:
    name: Wago
    url: https://addons.wago.io/addons/persolootroll
  script:
    - release.sh -ocelzLWHG

github:
  stage: deploy
  only: *releases
  environment:
    name: GitHub
    url: https://github.com/shrugal/PersoLootRoll/releases
  script:
    - release.sh -ocelzLAWG

gitlab:
  stage: deploy
  only: *releases
  environment:
    name: GitLab
    url: https://gitlab.com/shrugal/PersoLootRoll/releases
  script:
    - release.sh -ocelzLAWH
