image: registry.gitlab.com/shrugal/wow-packager:latest

stages:
  - build
  - test
  - deploy

.releases: &releases
  - /^\d[\d\.]*(-(debug|alpha|beta|stable)\d+)?$/

build:
  stage: build
  only: *releases
  script:
    - release.sh -d
  artifacts:
    paths:
      - .release/PersoLootRoll/
      - .release/*.zip

quicktest:
  stage: test
  except: *releases
  variables:
    GIT_DEPTH: 1
    GIT_SUBMODULE_STRATEGY: normal
  script:
    - echo TAG $CI_COMMIT_TAG
    - echo BRANCH $(git rev-parse --abbrev-ref HEAD)

test:
  stage: test
  only: *releases
  variables:
    GIT_DEPTH: 1
    GIT_SUBMODULE_STRATEGY: normal
  script:
    - lua Test.lua -b
  
curseforge:
  stage: deploy
  only: *releases
  environment:
    name: CurseForge
    url: https://wow.curseforge.com/projects/persolootroll
  script:
    - release.sh -ocelzWHG

wowinterface:
  stage: deploy
  only: *releases
  environment:
    name: WoWInterface
    url: https://www.wowinterface.com/downloads/info24667-PersoLootRoll.html
  script:
    - release.sh -ocelzLHG

github:
  stage: deploy
  only: *releases
  environment:
    name: GitHub
    url: https://github.com/shrugal/PersoLootRoll/releases
  script:
    - release.sh -ocelzLWG

gitlab:
  stage: deploy
  only: *releases
  environment:
    name: GitLab
    url: https://gitlab.com/shrugal/PersoLootRoll/releases
  script:
    - release.sh -ocelzLWH
